### ISSUE TITLE
Point A ==> B

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/NetworkProfiler#1]
We currently go from point A to outflow (or the last downstream segment we can traverse) but going point A to point B is really necessary. 

**The trick is to handle all the cases:**

1. How do we choose point A and point B in a way that makes sense to the user.
2. How do we handle a connection break between A and B
3. What if A and B has a reversed order.
4. What if _______ happens and we don't ___________.

**Comment by philipbaileynar** [comment]
For selecting A and B:

There's currently box  number 2 for selecting point A. Add another box for "Point B". In this box are 2 radio buttons. The first is "process network to outflow point". The second is "Process point to:" and then have a button next to it for grabbing the selected feature from the map. This point B remains fixed. Typically users will select a point near the outflow and leave that selection unchanged while they click around different point As and export CSVs.
