### ISSUE TITLE
Review Network Profiler documentation

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/NetworkProfiler#10]
Hey Philip,

 Before I show Jordan or Gary the new UI maybe I could get your feedback on it:

https://docs.google.com/a/northarrowresearch.com/document/d/1tZ-hK-MdyBFhlGNZHQaybpF7P3joi9vdlBERK7WaPEs/edit?usp=sharing

This is the doc I'm going to go through with them. Please feel free to add comments. Everything is malleable at this point so suggestions are welcome

**Comment by philipbaileynar** [comment]
Done. Looks good.
