### ISSUE TITLE
Auto-add CSV to map

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/NetworkProfiler#5]
The select projection problems mean that it can be a bit weird to get the imported CSV to have the right projection. 

Also there might be a good opportunity for learning the QGIs map projection window and providing a little guidance to users who want to re-add it in later.

**Comment by philipbaileynar** [comment]
Thinking more about this, there are some simple improvements that would really make this useful:

* Add the CSV directly underneath the network layer in the TOC.
* Default the symbology to be a fraction wider than than the network (say 25% wider line width). 

This should make it easier to see the result of the network profiler quickly without having to fiddle with symbology every time.

![2017-06-21_093940.png](https://codetreeusercontent.s3.amazonaws.com/uploads/c1200de3-640f-4289-a785-68acacac8612/2017-06-21_093940.png)
