### ISSUE TITLE
Network Profiler Graphic

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/NetworkProfiler#7]
We know that we need some kind of network profilder graphical output. These are typically long profile plots. Distance along the X axis and attribute value along the y axis. These could get very complicated with all variables on one plot and using different symbologies for different variables.

![2017-06-16_150612](https://user-images.githubusercontent.com/8645379/27246283-654b79a4-52a5-11e7-82e5-f3d9ee1c022a.png)

A first version could just be a subfolder next to the CSV called `Figs` that contains a separate MatPlot lib XY line plot for each ShapeFile attribute that is in the CSV. This is crude, but would enable rapid review of the values:

* X axis is distance, with zero representing the most upstream point in the analysis (point A)
  * Axis label would be "Distance (X)" where X is the horizontal units taken from the ShapeFile spatial reference.
* Y axis is the value of the attribute in question.
  * Axis label would simply be the name of the ShapeFile attribute.
* File name would be the ShapeFile attribute name. Perhaps prefixed with the feature ID of the upstream feature (point A) or maybe timestamped etc.

Other enhancement ideas:

* The network profiler UI could be enhanced to
  * allow selection of which attributes get plots.
  * attributes could be grouped onto axes.
  * attributes could be assigned different graphical display types. See the difference between confinement and stream power in the above example.

**Comment by MattReimer** [comment]
@philipbaileynar more research needed. I think we should avoid doing this in Q and instead ship an R script that does this

**Comment by philipbaileynar** [comment]
FYI I checked with Gary and he said that the graphic attached to this card was generated in Excel and then polished in Adobe Illustrator.

**Comment by joewheaton** [comment]
I think we should make a Riverscapes project for the network profiler prep and output.

**Comment by MattReimer** [comment]
@joewheaton so I think that's not quite what we want for 2 reasons:

1. The Network Profiler, as it currently stands, is a generic tool that exists independent of any riverscapes context. It parses any kind of shapefile you throw at it. The minute we force people to use it in a riverscapes way we exclude anyone who might find it useful for any other reason.
2. The tool doesn't "do" or manipulate anything. It only zooms in and visualizes an aspect what you already have as an output of another tool.  In that way, I don't really understand what a NetworkProfiler project "is" or represents.

It could be that we need to invent a kind of project that uses the network profiler tool as part of its process to derive an output that is part of Riverscapes but I see this as being a separate tool and not the profiler itself.

Thoughts?

**Comment by philipbaileynar** [comment]
The goal is the fastest, simplest XY plots. One for each attribute. Save them to PNG in same folder as the CSV output.
